parameters:
    caxy_xdomain.listener.xframe_option_header.class: Caxy\Bundle\XDomainBundle\EventListener\XFrameOptionHeaderListener

services:
    caxy_xdomain.listener.xframe_option_header:
        class: %caxy_xdomain.listener.xframe_option_header.class%
        arguments: [ %caxy_xdomain.allow_from% ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
